[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["python3.11 -m ensurepip && python3.11 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["flask db upgrade || true"]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
